### ISSUE TITLE
example of paths for windows

### ISSUE THREAD

**Issue by matthewkooshad** [LuisRibeiroo/easy-flutter-tests#1]
could you show what to use if the lib folder is at the below path on my disk? I can't seem to get this configured correctly. if you could help with an example, that'd be great!

"easy-tests.codePath": "c:\\dev\\app\\lib",
    "easy-tests.testsPath": "c:\\dev\\app\\lib\\test",

**Comment by LuisRibeiroo** [comment]
The default base folder is the open workspace root.
IE:
**Open workspace:** c:\dev\projectFolder

~~> *Relative path*
"easy-tests.codePath": "app\lib"
"easy-tests.testsPath": "app\lib\test"
